name: hutch-bunny-dev

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omop

  omop-lite:
    image: ghcr.io/health-informatics-uon/omop-lite
    depends_on:
      - db
    environment:
      DB_PASSWORD: postgres
      DB_NAME: omop
      SYNTHETIC: true
      SYNTHETIC_NUMBER: 1000

  adminer:
    image: wodby/adminer
    depends_on:
      - db
    restart: always
    ports:
      - 9000:9000
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DESIGN: pepa-linha

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  relay:
    image: ghcr.io/health-informatics-uon/hutch/relay:edge
    depends_on:
      - rabbitmq
      - db
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      DOTNET_Environment: Development
      ConnectionStrings__Default: Server=db;Port=5432;Database=hutch-relay;User Id=postgres;Password=postgres
      RelayTaskQueue__ConnectionString: amqp://user:password@rabbitmq:5672
      Obfuscation__LowNumberSuppressionThreshold: 0
      Obfuscation__RoundingTarget: 0
      UpstreamTaskApi__enable: false
      Database__ApplyMigrationsOnStartup: true
      Beacon__enable: true 
      DownstreamUsers__username__password: password  
      DownstreamUsers__username__Subnode: b8c58ab0-51c7-4842-ac96-efffc2c02472

  bunny:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - relay
    restart: always
    environment:
      DATASOURCE_DB_USERNAME: postgres
      DATASOURCE_DB_PASSWORD: postgres
      DATASOURCE_DB_DATABASE: omop
      DATASOURCE_DB_DRIVERNAME: postgresql
      DATASOURCE_DB_SCHEMA: public
      DATASOURCE_DB_PORT: 5432
      DATASOURCE_DB_HOST: db
      TASK_API_BASE_URL: http://relay:8080/link_connector_api
      TASK_API_USERNAME: username
      TASK_API_PASSWORD: password
      TASK_API_ENFORCE_HTTPS: false
      LOW_NUMBER_SUPPRESSION_THRESHOLD: 0
      ROUNDING_TARGET: 0
      POLLING_INTERVAL: 5
      COLLECTION_ID: b8c58ab0-51c7-4842-ac96-efffc2c02472
      BUNNY_LOGGER_LEVEL: "INFO"
      PYTHONUNBUFFERED: "1"
      # Observability config
      OTEL_ENABLED: true 
      OTEL_SERVICE_NAME: "hutch-bunny"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      # Distribution query cache config 
      CACHE_ENABLED: true 
      CACHE_DIR: /app/bunny_cache
      CACHE_TTL_HOURS: 0.25
      CACHE_REFRESH_ON_STARTUP: true 
