name: Check Code Quality

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  ruff:
    name: Run Ruff
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Run Ruff
        uses: astral-sh/ruff-action@39f75e526a505e26a302f8796977b50c13720edf # v3.2.1

