name: Run Tests

on:
  pull_request:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: uv sync
        run: uv sync --frozen --dev

      - name: Run tests
        run: uv run pytest tests
