# This workflow is used to tag an existing container image with a semver version
# and create a GitHub Release
name: Publish a Versioned Release

on:
  push:
    tags:
      - v*

env:
  image-name: hutch/bunny
  repo-owner: ${{ github.repository_owner }}
  registry: ghcr.io

jobs:
  version-tag:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # read source version
      - uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: pyproject.toml
          field: project.version
      
      # check tag version against source version
      - name: A/B Check
        if: v${{ steps.read_version.outputs.value }} != ${{ github.ref_name }}
        run: |
          echo "::error::Tag version doesn't match source version"
          exit 1

      # check image exists for commit
      - uses: tyriis/docker-image-tag-exists@v2.1.0
        with:
          registry: ${{ env.registry }}
          repository: ${{ env.repo-owner }}/${{ env.image-name }}
          tag: ${{ github.sha }}

      # standard login to the container registry
      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.registry }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      # We still use the metadata action to help build out our tags from the Workflow Run
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.registry }}/${{ env.repo-owner }}/${{ env.image-name }}
          tags: | # new tags only
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      # apply the new tags to the existing images
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ${{ env.registry }}
          repository: ${{ env.repo-owner }}/${{ env.image-name }}
          target: ${{ github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          token: ${{secrets.GITHUB_TOKEN}}
